### ISSUE TITLE
Global Include Paths auto detection changes order and breaks #include_next for system headers

### ISSUE THREAD

**Issue by l4l** [CoatiSoftware/CoatiBugTracker#101]
Other way some projects fail

![screenshot- - -21-14 03 31-msk-2016](https://cloud.githubusercontent.com/assets/5658339/16227420/7e7e683c-37c1-11e6-9beb-c7c62bb4ae86.png)

**Comment by egraether** [comment]
First an explanation: `#include_next` is used to define which **Include Path** should be used to find a certain file, so you can define the correct file when using multiple versions.

In your case the included file is not found anymore because the order of the **Include Paths** or **Global Include Paths** is not the same your compiler usually uses.

We just looked into this and found that our auto detection for **Global Include Paths** does not keep the original order, which probably causes this issue. We will fix this issue.

For now you need to manually change the order of your **Global Include Paths**. Please have a look at our [documentation](https://www.coati.io/documentation/#FindingSystemHeaderLocations) to find out the original order for your platform.

**Comment by l4l** [comment]
Ok, it solved the problem, thanks

**Comment by egraether** [comment]
Fixed with 0.7.0.10
Detected header search paths keep original order now.
