### ISSUE TITLE
No CDB file generated by visual studio for rippled

### ISSUE THREAD

**Issue by bachase** [CoatiSoftware/CoatiBugTracker#232]
Version: Coati 0.9.0
Platform: VS Community Edition 2015

The create compilation database window pops up briefly then closes.  I don't see any CDB file generated on disk.

Steps to reproduce: 
1. Clone https://github.com/ripple/rippled
2. Checkout develop branch
3. Open Builds/VisualStudio2015/ripple.sln
4. Select Coati -> Export CDB
5. Choose RippleD project, Configuration debug.classic, Platform x64, CDB name ripple and C Standard c11.

**Comment by wrongway88** [comment]
Thanks for the report @bachase, I'll take a look at it right away.

Might be related to a similar report we got via mail. I'll post as soon as I know more.

**Comment by wrongway88** [comment]
An unhandled exception occured while parsing, caused by an error during VC Project Configuration retreival. This is now fixed.

Also, an updated version of the plugin is on it's way, probably to be released later this week (but no promisses about the exact date). This will include (file and console)logging and better exception handling.

**Comment by bachase** [comment]
Awesome.  Thanks for taking a look so quickly!

**Comment by wrongway88** [comment]
The new version of the plugin is included in last week's update (Coati 0.9.23 - https://www.coati.io/downloads)

CDB creation should now work. If there are still problems the plugin has optional file logging now, it can be turned on in VS->Tools->Options->Coati

**Comment by bachase** [comment]
Works now.  Thank you!
