### ISSUE TITLE
Coati crashes trying to parse vtk 

### ISSUE THREAD

**Issue by HarryDC** [CoatiSoftware/CoatiBugTracker#252]
My environment is Coati 0.9.23, Visual Studio 15, vtk 6.3, I create a CDB in visual studio for the vtk project, excluding the example files, the import into coati seems to work fine but coati will consistently crash after starting to parse the project

**Comment by egraether** [comment]
Our next release will include some crash fixes during indexing.

Can you please enable Logging in the Preferences and send us the last 20 lines in the log file when the crash happens. Find log files via the Menu in "Help -> Show Log Folder"

**Comment by HarryDC** [comment]
I have the same problem with another project, one that I have parsed mostly successfully via the Visual Studio import, I ran it and here is the tail of the log file 

[oss-parse-failure-12-01-2016-tail.txt](https://github.com/CoatiSoftware/CoatiBugTracker/files/625249/oss-parse-failure-12-01-2016-tail.txt)

**Comment by mlangkabel** [comment]
From the log file I'm guessing that you have set up the Coati project to index the Visual Studio standard headers in addition to your own project's source files. Of course this should be possible but we know that the current release has some issues there. As @egraether mentioned before these crashes will be fixed in our next release.

For now you have the option to disable indexing these specific headers. Personally I do that all the time for my own projects because Coati is much faster when skipping indexing the std headers and until now I just never wanted to navigate that code. (When removing these headers form the index you will still be able to see usages of the std library in your own code.)

To do so you just need to open your "Edit Project" dialog, find the "Indexed Header Paths" listbox and remove all the paths that point to `C:/Program Files (x86)/Microsoft Visual Studio 14.0/` and its subdirectories.

**Comment by HarryDC** [comment]
That helped, yes and it did speed up parsing by quite a bit, it was a misunderstanding on what actually needs to be indexed, thanks

**Comment by mlangkabel** [comment]
Fixed all crashes when idexing the std headers on Windows, Mac and Linux with the new release version of Coati 0.10.0
