### ISSUE TITLE
Can't index project of Nordic SDK12.2.0. 

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#291]
To reproduce:
1. download Nordic nRF SDK: http://www.nordicsemi.com/eng/nordic/Products/nRF52832/nRF5-SDK-zip/54281
2. unzip contents to selected directory
3. Edit attached coati project file to fix paths, replace 'C:/git/smablo/nordic-sdk12/nRF5x_SDK12' with your Nordic SDK direcory
4. Run coati and observe error "Not enough resources to run example" - this is indicator that preprocessor doesn't take into account define BOARD_PCA10040 despite what Coati project config says. If the same is true for other defines then it's no wonder why Coati doesn't see many SDK modules - they all are inside #ifdef X blocks to strip unused code sections

**Comment by wrongway88** [comment]
I'll need that project file to take a look at it, please make it available

**Comment by egraether** [comment]
Sorry, overlooked that.
Project file: [Nordic-SDK test.txt](https://github.com/CoatiSoftware/CoatiBugTracker/files/714879/Nordic-SDK.test.txt)
(I had to rename to `.txt` to make the upload work. Rename to `.coatiproject` after download)

**Comment by wrongway88** [comment]
I've recreated the error, I'm looking into it right now

**Comment by wrongway88** [comment]
Short update:
I checked and made sure that all defines are passed on for parsing.
The issue seems to be rooted deeper than that, I'll report as soon as I have news.

**Comment by mlangkabel** [comment]
It looks like the issue is in the attached project file. It provides a lot of compiler flags (e.g. `DEBUG=1`) that look like their indention is to specifying a define. 

For these compiler flags to be working correctly you need to tell the compiler what kind of flag you want to add (e.g. provide a define, turn all warnings into errors, ...)

To provide a define, please use the following syntax (as listed in the "Compiler Flags" help dialog):
`-D DEBUG=1`
