### ISSUE TITLE
methods undefined

### ISSUE THREAD

**Issue by TonnyTao** [CoatiSoftware/CoatiBugTracker#305]
Mac
Coati 0.10.0

These two methods in RxJavaPlugins.java have different view in graphic. I expect the appearance of them should be same.

```java
    public static <T> MaybeObserver<? super T> onSubscribe(Maybe<T> source
        , MaybeObserver<? super T> subscriber) {

    }

    public static <T> Maybe<T> onAssembly(Maybe<T> source) {

    }
```

![](https://i.imgsafe.org/d2824886b5.png)

**Comment by mlangkabel** [comment]
Thanks for reporting! This is surely an issue. I guess that those duplicates have been resolved with different type strings in theirs signatures. We will look into that as soon as possible!

**Comment by mlangkabel** [comment]
Ok, I cloned the repo in order to reproduce this issue. The code base contained multiple versions of those `onAssemble` and `onSubscribe` methods with different signatures. So it's ok for Coati to show different versions of those. However I am able to reproduce the `undefined` state of the `onAsseble` methods. This is clearly an issue.

Good news: I tested with the dev build of Coati that will be downloadable on our next release and everything looks fine there. Not a single undefined symbol in the RxJavaPlugins class anymore :)
