### ISSUE TITLE
VS plugin: Menu item "Create Coati Project" not clickable

### ISSUE THREAD

**Issue by cwinkler89** [CoatiSoftware/CoatiBugTracker#32]
The Coati menu itself is shown, but the only entry "Create Coati Project" is grayed out and not clickable. VS Version 2015 (Community), Coati Version 0.5.0.4

**Comment by wrongway88** [comment]
Hey ChriZzZ, do have a (c/c++) solution loaded? If not that's on purpose since the Coati project would be based on the current solution. Otherwise it would be a bug.

**Comment by ChriZzZ** [comment]
YES. I have a Solution with over 20 projects loaded, ever tried that much? I also can not load the Solution from Coati itself. If I try Coati crashes.

**Comment by egraether** [comment]
test comment

**Comment by wrongway88** [comment]
@egraether Test response

@ChriZzZ Thanks for your response. We have tested big solutions, layouts of individual VS solution and project files seem to vary however.

Is the specific project you are working on available? It would make replicating the issue much faster. In any case, I'll look into it.

**Comment by ChriZzZ** [comment]
Unfortunately the project is not available. The behavior is the same as if you try to open a solution that requires elevated rights. I should note that I am using Win10 and YES I tried running VS as administrator. If I create a Project inside C\:Program Files(x86)\SomeSubFolder and then run vs without admin mode then the Coati Menu is also greyed out and can not be clicked. Maybe this information helps.

**Comment by ChriZzZ** [comment]
PS: Opening a single project from that solution via the vcxproj file renders the menu in color and makes it clickable. But nothing happens in Coati.

**Comment by wrongway88** [comment]
That information did help, I was able to recreate the behaviour. I'll be working on fixing it.

However I'm not sure what you mean by opening the project file directly. Even removing the .sln file would cause VS to create a new .sln file and put the project in it.
http://stackoverflow.com/questions/4679282/how-can-i-open-a-project-without-opening-its-associated-solution-in-visual-studi

**Comment by ChriZzZ** [comment]
What I meant by opening a single project:

Each project comes with a vcxproj file. Opening the Solution (.sln) loads all projects (.vcxproj) at once. Opening a single vcxproj file opens a auto generated solution loading only this single project.

**Comment by wrongway88** [comment]
@ChriZzZ Thanks again for the feedback. I've spend some time now with this.
As far as I can tell the issue is not related to access rights. I could however recreate the described behaviour. Could have something to do with project/solution upgrade to a newer VS version.

So @ChriZzZ, I wonder whether your project was auto-upgraded at some point by VS? Also, did you ever try using the "Create Project" option with the solution in a non-restricted folder?

As for opening single vcxproj files, this was related to the temporary VS solution not actually being there in the file system. Coati usually uses the sln file for parsing. I modified it so it can now also deal with single vcxproj files.

**Comment by ChriZzZ** [comment]
Yes, at least how far i remember, it is auto-upgraded.
Yes, the Coati Menu is working fine if I create a new project in a non-restricted folder.
