### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by MojaveWastelander** [CoatiSoftware/CoatiBugTracker#52]
Here are some suggestions after using application few times:
- In Windows 7+ dragging a window to screen upper point will maximize it, this works as expected for main window but detached windows need to be resized manually
- Memorize windows positions/sizes (like e.g. a multimonitor configured Visual Studio)
- Ctrl + Mouse Wheel is global per application and have a high latency (it should be per specific view)
- Holding Ctrl and making few scrolls with  mouse wheel will make application unusable and it will try to apply resize for each wheel step
- In classes with many items Ctrl + Shift + Mouse wheel can be used for fast scrolling (like using page up/page down)
- When there are more items in a view and scrolling is needed mouse wheel can be used for that purpose in addition to dragging or using scroll bar (something like that is in Matlab)
- Mouse gestures for back (Right Click -> Left Click) and forward (Left Click -> Right Click), like in Opera/Vivaldi browsers
- Ability to filter/limit displayed data. I have a small project with about 10 classes and few support functions/templates. When I parse the project it displays everything it found (some boost libs, cppformat, Catch etc.), thus I see a lot of info that I'm interested right now to see.
- Basic types like char, int, float and STL containers are displayed as undefined types
- A Log window will be useful to see what is happening and that the application is actually working (status bar notification is not a reliable indicator of activity)

**Comment by egraether** [comment]
@MojaveWastelander thanks for your feedback! I splitted some things into separate issues and I have some questions:

1. I opened #53
2. This should work already. What platform version are you using?
3. I guess what you really want is a zooming the graph with mouse wheel? I opened #54
4. This was fixed already, it will be in the next release: #44
5. Isn't this what currently happens when scrolling with mouse wheel in the graph view?
6. See 3.
7. I opened #55. FYI: We already support the mouse back and forward buttons.
8. The problem with filtering out information is that you also lose information. We are thinking about ways to do this. How do you imagine it? I opened #57
9. We have an open discussion on this, but not sure what to do yet: #2 
10. You are right. I opened #56

**Comment by MojaveWastelander** [comment]
I tested application on Windows 7 and 10, quadcore CPU, 8GB+ RAM and SSD.
2. Strange, it is working (for some reason it didn't work earlier).
3. Currently zooming with mouse zoom whole interface, but it should change only current view. Also it seems to be dependent on project size (on root view), it works well with test projects, but on my project with order of hundreds of classes/functions/files it make one zoom step in few seconds, with a bigger project it is even slower (it doesn't matter if code view is being shown). When zooming in some specific item zoom is fast enough, but sometimes it jumps back to root view and starts processing zoom messages as being in root (meaning slowly).
5. Hmm, actually it is. 
6. This is related to root view, when opening a project with a lot of  items to scroll with mouse Ctrl + Alt + Shift + Mouse wheel combination is used, I think in this case just using mouse wheel would be enough.
8. Right now find box works only with fuzzy search, using regular expressions to search for specific names patterns might be a method (this will filter out many items that are usually displayed by fuzzy searching) . Filtering info in root view should focus on important stuff, in this case specific libraries should be parsed but not displayed in root, but those hidden items should be present when showing in references (it is meant to focus on the project at hand, because having hundreds of unrelated items in root view just make it harder to concentrate).
I didn't have much time looking into these issues closer, just wrote them as quick remarks. I didn't used application that long to give more detailed suggestions, maybe later I will.

**Comment by egraether** [comment]
Thank you for replying.
3. I added zoom with `Shift + mouse wheel` #54 for the graph, it will be in the next release. This zoom does not reload the UI on every zoom step, so it's much smoother. I don't think that zooming in the other views makes much sense, you just set the font size to a well readable size and then you keep it that way. Why do you want to zoom in the code view?
6. Are you talking about scrolling left and right? What does Ctrl + Alt + Shift + Mouse wheel do?
8. Yes, regular expressions might be nice for searching, I opened #59.
8b. The user can define which things are important during project setup by providing only the project files he/she is interested in. Everything in these files will be the focus. All symbols of other files, such as libraries and frameworks, will be shown as undefined nodes and usually be hidden from the user in the graph.

**Comment by MojaveWastelander** [comment]
6. Combination works as fast scrolling in root view, like using left and right arrows keys, but skipping over more items.

**Comment by egraether** [comment]
6. I see, that's the default scroll area behavior. I'm still not sure which way to go with mouse wheel behavior, since changing the behavior would also affect trackpad users. For now I think it's best to stick to the defaults.

@MojaveWastelander Thank you for all your feedback here, we appreciate it a lot! I'm closing this issue now. Feel free to open new issues for more questions and ideas.
