### ISSUE TITLE
Crash at startup on Windows

### ISSUE THREAD

**Issue by speps** [CoatiSoftware/CoatiBugTracker#60]
Downloaded the trial version (`Coati_Trial_0_5_1_21_Windows_32bit.zip`), installed it, got this when running.

![2016-03-17 13_56_28-coati trial exe - system error](https://cloud.githubusercontent.com/assets/16678/13848168/7b230f2c-ec48-11e5-8f9b-65abe87355bc.png)

**Comment by mlangkabel** [comment]
@speps: For windows Coati requires some components of the Visual C++ Redistributable Packages. This package is defines as a pre-install requirement of the Coati installer so that it should be downloaded and installed automatically. 
In your case it seems like the installer missed that requirement, but you can easily fix it by downloading and installing the package manually ([link](https://www.microsoft.com/en-us/download/details.aspx?id=48145), choose the x86 version).
Thanks for reporting this issue. We will make sure that this information is added to the documentation!

**Comment by mlangkabel** [comment]
Since the pre-requirements check of the installer is not working correctly on every system we decided to ship the required dlls with the exe directly.
This is fixed with 0.5.3.38
