### ISSUE TITLE
Graph view is slow on many items displayed

### ISSUE THREAD

**Issue by MojaveWastelander** [CoatiSoftware/CoatiBugTracker#61]
For example I use [ArxLibertatis](https://github.com/arx/ArxLibertatis) source code. **Entity** class is referenced 1554 times, when all of them are expanded interface is very slow.

**Comment by mlangkabel** [comment]
@MojaveWastelander: I just tested that case myself. In general Coati tries to keep the graph size to a minimum so that the graphs stay readable but of course you can make Coati display everything, if you want to. With this case you really found a great stress test for the graph view. Thanks for reporting!
For our next release we are planning on optimizing the performance of the UI so that the interaction stays smooth even for these extreme cases.

**Comment by egraether** [comment]
Improved edge drawing performance with 0.5.2.14
