### ISSUE TITLE
*inc  files is not supported

### ISSUE THREAD

**Issue by rojaster** [CoatiSoftware/CoatiBugTracker#98]
May it is a feature.

```cpp

...

#include <stddef.h>
#include "MyClass.h"
#include "somefilegeneratedfromouthere.inc"
...
//Look, if you get *.inc file when it parses some sources , I just would try to find it near. 
//Keep in mind  just simple rule about #include "...." - look up firstly into current directory 

```

**Comment by egraether** [comment]
The file ending of included files does not matter any more since Coati 0.7
Here is a simple sample project with 3 files and pictures:

```
// header.h

float pow(float base, unsigned int exp)
{
	if (exp == 0)
	{
		return 1;
	}

	return base * pow(base, exp - 1);
}
```

```
// gen/generated.inc

#define PI 3.1415f
```

```
// main.cpp

#include "header.h" // in same directory
#include "generated.inc" // in directory 'gen', found via include path

int main()
{
	float pi5 = pow(PI, 5);

	return 0;
}
```
![filetree](https://cloud.githubusercontent.com/assets/201867/16134681/dea4e886-341e-11e6-8985-6acabfe65853.png)
<img width="784" alt="project" src="https://cloud.githubusercontent.com/assets/201867/16134689/e500ebda-341e-11e6-8fd4-583ddefd617e.png">
<img width="1317" alt="coati" src="https://cloud.githubusercontent.com/assets/201867/16134690/e7a46434-341e-11e6-836e-4b49f8d0d9e3.png">


Coati analyses the source file `main.cpp` and finds the included file `header.h` in the same direcory. I had to add an Include Path for the directory `gen/` so that `generated.inc` could be found. The file `generated.inc` is also analyzed because it's within the Project Path `src/`, the file ending did not matter.

Does this clear things up? What errors are you getting?

**Comment by rojaster** [comment]
Hmmm. what should i do if this files will generate by cmake during builds?

**Comment by egraether** [comment]
Then you need to add the cmake build directory where this file is located to the Include Paths.

**Comment by rojaster** [comment]
Yes,  i added this directory too

**Comment by egraether** [comment]
Depending on where it is exactly located you might need to add a more specific path.
Let's assume the `.inc` file is included like this:

```
// file.cpp
#include "types.inc"
...
```
and `file.cpp` is located at `.../project_dir/src/file.cpp`. Then cmake will put the `.inc` file into `.../project_dir/build/src/types.inc`.

The correct Include Path for Coati is then `.../project_dir/build/src`

**Comment by rojaster** [comment]
ok 👍
